// PrivyLens AI — Compliance Report Templates & Exporter Engine

export const REPORT_TEMPLATES = [
  {
    templateId: 'executive',
    name: 'Executive Privacy Brief',
    description: 'High-level scorecard summarizing trust metrics, top risks, and leadership action items.',
    format: 'PDF',
    badge: 'Popular',
    icon: 'FileBarChart',
    color: 'from-primary/20 to-secondary/20',
  },
  {
    templateId: 'compliance',
    name: 'Regulatory Compliance Audit',
    description: 'Statutory compliance evaluation against DPDP Act 2023, DPDP Rules 2025, and NIST frameworks.',
    format: 'PDF',
    badge: 'Legal',
    icon: 'Scale',
    color: 'from-amber-500/20 to-orange-500/20',
  },
  {
    templateId: 'benchmark',
    name: 'Multi-Service Benchmark',
    description: 'Side-by-side comparative matrix evaluating privacy scores across audited applications.',
    format: 'CSV',
    badge: 'Analytical',
    icon: 'GitCompare',
    color: 'from-blue-500/20 to-cyan-500/20',
  },
  {
    templateId: 'manifest',
    name: 'Full Clause Manifest',
    description: 'Exhaustive data export of verbatim legal text, severity ratings, and statutory citations.',
    format: 'JSON',
    badge: 'Developer',
    icon: 'FileCode',
    color: 'from-emerald-500/20 to-teal-500/20',
  },
];

// Generates actual downloadable plain-text or structured export content
export const generateReportFileContent = (report) => {
  if (report.format === 'JSON') {
    return JSON.stringify(
      {
        reportId: report.reportId || report.id,
        title: report.title,
        service: report.serviceName,
        trustScore: report.trustScore,
        riskLevel: report.riskLevel,
        complianceBadges: report.complianceBadges || ['DPDP Act 2023 Verified'],
        generatedAt: report.generatedAt || new Date().toISOString(),
        summary: report.summary,
        keyFindings: report.keyFindings || [],
        meta: {
          engine: 'PrivyLens AI Compliance Engine v2.4',
          statutoryFrameworks: ['DPDP Act 2023', 'DPDP Rules 2025', 'NIST Privacy Framework v1.0'],
        },
      },
      null,
      2
    );
  }

  if (report.format === 'CSV') {
    let csv = 'Finding_ID,Category,Service,Risk_Severity,Description\n';
    (report.keyFindings || []).forEach((finding, idx) => {
      csv += `${idx + 1},Privacy Finding,"${report.serviceName}","${report.riskLevel}","${finding.replace(/"/g, '""')}"\n`;
    });
    return csv;
  }

  // Default PDF/Text Executive Brief
  return `================================================================================
                    PRIVYLENS AI — EXECUTIVE PRIVACY REPORT
================================================================================
Report ID      : ${report.reportId || report.id}
Title          : ${report.title}
Target Service : ${report.serviceName} (${report.serviceId || 'Active'})
Trust Score    : ${report.trustScore} / 10
Risk Level     : ${(report.riskLevel || 'Moderate').toUpperCase()}
Generated At   : ${new Date(report.generatedAt || Date.now()).toUTCString()}
Auditor        : PrivyLens AI Grounded Engine

--------------------------------------------------------------------------------
1. EXECUTIVE SUMMARY
--------------------------------------------------------------------------------
${report.summary || 'Privacy audit completed successfully.'}

--------------------------------------------------------------------------------
2. KEY FINDINGS & CLAUSE CITATIONS
--------------------------------------------------------------------------------
${(report.keyFindings || []).map((f, i) => `[${i + 1}] ${f}`).join('\n')}

--------------------------------------------------------------------------------
3. STATUTORY COMPLIANCE STATUS
--------------------------------------------------------------------------------
${(report.complianceBadges || ['DPDP Act 2023 Compliant', 'NIST Framework Aligned']).join(' | ')}

================================================================================
Generated by PrivyLens AI (https://privylens.ai)
Deterministic Evidence Grounding & Persona Privacy Intelligence
================================================================================`;
};
